version: '3'

services:
  postgres-db3:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitor_db
    ports:
      - "5435:5432"
    volumes:
      - db-data1:/var/lib/postgresql/data

  monitoring-service:
    image: monitoring-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8082:8082" #maybe 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db3:5432/monitor_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-db3
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db-data1:
